const types = {
  OPEN_MODAL_QR_CODE_PIX: 'OPEN_MODAL_QR_CODE_PIX',
  CLOSE_MODAL_QR_CODE_PIX: 'CLOSE_MODAL_QR_CODE_PIX',

  OPEN_MODAL_ADD_CARD: 'OPEN_MODAL_ADD_CARD',
  CLOSE_MODAL_ADD_CARD: 'CLOSE_MODAL_ADD_CARD',

  ADD_CARD_REQUEST: 'ADD_CARD_REQUEST',
  ADD_CARD_SUCCESS: 'ADD_CARD_SUCCESS',

  OPEN_MODAL_TICKET: 'OPEN_MODAL_TICKET',
  CLOSE_MODAL_TICKET: 'CLOSE_MODAL_TICKET',
};

export default types;
